language: ruby
rvm:
  - 2.1

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - npm install -g grunt-cli

install:
  - bundle install
  - npm install grunt grunt-html --save-dev

script:
  - bundle exec jekyll build --drafts
  - grunt test
  - bundle exec htmlproof ./_site

notifications:
  email: false

# whitelist
branches:
  only:
    - gh-pages
