markdown: redcarpet
highlighter: null
permalink: /:title

url: /grally.github.io
baseurl: /grally.github.io

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
