name: gRally dev corner
description: gRally Sim under the hoods
meta_description: "gRally sim under the hoods"

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://dev.grally.net'
google_analytics: 'UA-XXXXXXXX-X'
permalink: /archive/:year/:month/:day/:title/

# Details for the RSS feed generator
url:            'http://dev.grally.net'
author:         'ghiboz'

# Github repositories
github_user: ghiboz
github_repo_url: https://github.com/gRally/gRally.github.io

# Twitter
twitter_user: ghiboz
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: ghiboz
disqus_show_comment_count: true
