# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            gRally
tagline:          all terrain simulator
url:              http://grally.github.io
paginate:         1
baseurl:          /
author:
  name:           ghiboz
  url:            https://twitter.com/ghiboz

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/
  wiki:           https://github.com/gRally/gRally.github.io/wiki
